# Creating Arrays in Python
An array in Python is a data structure used to store multiple elements of the **same data type** in a single variable. The Arrays are useful for handling large collections of data efficiently.
## 1. Using Lists:

In [7]:
my_list = [1, 2, 3, 4, 5]
print (my_list)

[1, 2, 3, 4, 5]


## 2. Using the array Module:
The array module provides a more memory-efficient way to create arrays. Unlike lists, arrays created using the array module can only store items of the same type. The first argument to the array function specifies the type of the elements. For example, 'i' stands for signed integers and 'f' stands for floating-point numbers.

In [14]:
import array as arr
my_array = arr.array('i', [1, 2, 3, 4, 5])
print (my_array)

array('i', [1, 2, 3, 4, 5])


# Array Operations

## 1. Accessing Elements:

In [15]:
print(my_array[0]) 
print(my_array[2])

1
3


## 2. Modifying Elements:

In [16]:
my_array[0] = 10
print(my_array)

array('i', [10, 2, 3, 4, 5])


## 3. Appending Elements:

In [17]:
my_array.append(6)
print(my_array)

array('i', [10, 2, 3, 4, 5, 6])


## 4. Inserting Elements:
Use the insert method to insert an element at a specific position.

In [18]:
my_array.insert(1, 20)
print(my_array)


array('i', [10, 20, 2, 3, 4, 5, 6])


## 5. Removing Elements:
Use the remove method to remove the first occurrence of a specific element.

In [19]:
my_array.remove(20)
print(my_array)

array('i', [10, 2, 3, 4, 5, 6])


## 6. Popping Elements:
Use the pop method to remove and return the last element of the array.

In [20]:
last_element = my_array.pop()
print(my_array)
print(last_element)

array('i', [10, 2, 3, 4, 5])
6


## Array Slicing
The syntax for slicing is array[start:stop:step].

In [21]:
sliced_array = my_array[1:4] # Extract elements from index 1 to 3
print(sliced_array)

array('i', [2, 3, 4])


# Multidimensional Arrays
## 1. Using Nested Lists:

In [22]:
matrix = [
[1, 2, 3],
[4, 5, 6],
[7, 8, 9] ]
print(matrix[0][1])

2


## 2. Using NumPy:

### Load in NumPy

In [1]:
import numpy as np

### The Basics

In [2]:
matrix = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9] ])
print(matrix[0, 1])

2


In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Get Dimension
print(f"a.ndim: {a.ndim}")
print(f"b.ndim: {b.ndim}")

a.ndim: 1
b.ndim: 2


In [7]:
# Get Shape
print(f"a.shape: {a.shape}")
print(f"b.shape: {b.shape}")

a.shape: (3,)
b.shape: (2, 3)


In [8]:
# Get Type
print(f"a.dtype: {a.dtype}")
print(f"b.dtype: {b.dtype}")

a.dtype: int32
b.dtype: float64


In [9]:
# Get Size
print(f"a.itemsize: {a.itemsize}")
print(f"b.itemsize: {b.itemsize}")

a.itemsize: 4
b.itemsize: 8


In [10]:
# Get total size
print(f"a.nbytes: {a.nbytes}")
print(f"b.nbytes: {b.nbytes}")

a.nbytes: 12
b.nbytes: 48


In [11]:
# Get number of elements
print(f"a.size: {a.size}")
print(f"b.size: {b.size}")

a.size: 3
b.size: 6


### Accessing/Changing specific elements, rows, columns, etc

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
# Get a specific element [r, c]
a[1, 5]

np.int64(13)

In [14]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [16]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [17]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [18]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
# Get specific element (work outside in)
b[0,1,1]

np.int64(4)

In [23]:
# replace 
b[:,1,:] = [[9, 9],[8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing Different Types of Arrays

In [24]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [27]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [28]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [29]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.07723579, 0.84691994],
       [0.57148364, 0.83107102],
       [0.60017   , 0.98268353],
       [0.28000256, 0.37136659]])

In [30]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 7,  5,  0],
       [ 6,  3,  5],
       [-3, -3,  2]], dtype=int32)

In [31]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [33]:
output = np.ones((5,5))
print(f"output:\n{output}")

z = np.zeros((3,3))
z[1,1] = 9
print(f"z:\n{z}")

output[1:-1,1:-1] = z
print(f"output:\n{output}")

output:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
z:
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
output:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [35]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(f"a: {a}")
print(f"b: {b}")

a: [1 2 3]
b: [100   2   3]


### Mathematics

In [36]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [37]:
a + 2

array([3, 4, 5, 6])

In [38]:
a - 2

array([-1,  0,  1,  2])

In [40]:
a * 2

array([2, 4, 6, 8])

In [39]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [41]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [42]:
a ** 2

array([ 1,  4,  9, 16])

In [43]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

In [44]:
a = np.ones((2,3))
print(f"a:\n{a}")

b = np.full((3,2), 2)
print(f"b:\n{b}")

output = np.matmul(a,b)
print(f"output:\n{output}")

a:
[[1. 1. 1.]
 [1. 1. 1.]]
b:
[[2 2]
 [2 2]
 [2 2]]
output:
[[6. 6.]
 [6. 6.]]


In [45]:
# Find the determinant
c = np.identity(3)
print(f"c:\n{c}")
det_c = np.linalg.det(c)
print(f"Determinant of c: {det_c}")

c:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Determinant of c: 1.0


#### Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
- Determinant
- Trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norm
- Inverse
- Etc...

### Statistics

In [46]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.min(stats)

np.int64(1)

In [48]:
np.max(stats, axis=1)

array([3, 6])

In [49]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [51]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [52]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

##### Boolean Masking and Advanced Indexing

In [ ]:
(~((filedata > 50) & (filedata < 100)))